apiVersion: apps/v1
kind: Deployment
metadata:
  name: bao-nodejs-cicd-demo
  namespace: bao-cicd-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bao-nodejs-cicd-demo
  template:
    metadata:
      labels:
        app: bao-nodejs-cicd-demo
    spec:
      containers:
        - name: bao-nodejs-cicd-demo
          image: IMAGE_URI_PLACEHOLDER
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: bao-nodejs-cicd-demo-svc
  namespace: bao-cicd-lab
spec:
  type: LoadBalancer
  selector:
    app: bao-nodejs-cicd-demo
  ports:
    - port: 80
      targetPort: 3000
