apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-cicd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-cicd-demo
  template:
    metadata:
      labels:
        app: nodejs-cicd-demo
    spec:
      containers:
        - name: nodejs-cicd-demo
          image: 470562161805.dkr.ecr.ap-southeast-1.amazonaws.com/nodejs-cicd-demo:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-cicd-demo-svc
spec:
  type: LoadBalancer
  selector:
    app: nodejs-cicd-demo
  ports:
    - port: 80
      targetPort: 3000
